### ISSUE TITLE
grunt-ts support

### ISSUE THREAD

**Issue by ConneXNL** [tschaub/grunt-newer#38]
I am trying to use grunt-ts along with grunt-newer but I am facing some problems. I am using the
ts {
  test { 
      {
       src : ["test.ts", "test_2.ts",
       outDir: tmp/
     }
  }
}

The problem seems to be that the outDir configuration is not there when i am using newer:ts.

Running "newer:ts:client_ts" (newer) task
Options: cache="D:\\Localhost\\www\\won\\node_modules\\grunt-newer\\.cache"
Files: test.ts test_2.ts

Running "ts:test" (ts) task
Verifying property ts.test exists in config...OK
Files: test.ts -> [no dest]
Options: allowBool, allowImportModule=false, compile, declaration=false, mapRoot="", module="amd", noImplicitAny=false, noResolve=false, comments=null, removeComments=null, sourceMap=false, sourceRoot="", target="es5", verbose=false
Warning: Cannot call method 'indexOf' of undefined Use --force to continue.

Aborted due to warnings.

**Comment by tschaub** [comment]
It sounds like `grunt-ts` doesn't follow Grunt's conventions for [configuring `src` and `dest` files](http://gruntjs.com/configuring-tasks#files).

**Comment by tschaub** [comment]
I'm going to fold this into #67 for tracking all `grunt-ts` related issues.
