### ISSUE TITLE
Plugin don't see the New files for - "Tasks that specify only "src" files"

### ISSUE THREAD

**Issue by trikon** [tschaub/grunt-newer#58]
```
imagemin: {
        all: {
            files: [{
                expand: true,
                cwd: 'images/',
                src: '**/*.{gif,png,jpg,jpeg}',
                dest: 'images/'
            }]
        }
    }
```

After first run(when the cache has been created), the `grunt-newer` don't see NEW added images in `images/` folder:). It sees only changed images...
I have such feeling that the plugin is do not stores `src`'s folder files list in plugin's cache...

**Comment by tschaub** [comment]
Please report the output from `grunt --verbose imagemin` and `grunt --verbose newer:imagemin`.
