### ISSUE TITLE
grunt-tslint runs again all the files with newer

### ISSUE THREAD

**Issue by mvidailhet** [tschaub/grunt-newer#67]
My grunt-ts config:
```
        tslint: {
            options: {
                configuration: grunt.file.readJSON("tslint.json")
            },
            all: {
                src: ["app.ts", "**/*.ts", "!node_modules/**/*.ts"]
            }
        },
```

If I run newer:tslint:all in my watch task, it still runs again all the ts files.

**Comment by tschaub** [comment]
@mvidailhet could you publish a repository that I could clone to reproduce this problem?  Or a gist with enough files to easily get things set up.

**Comment by mvidailhet** [comment]
Hi @tschaub,

I'm so sorry, but I actually meant grunt-tslint and not grunt-ts.

For the 2 issues you linked, seems that the answer lies in the "fast" option of grunt-ts. The fast options actually allows to recompile only changed files (like grunt-newer does).

If you specify a "out" directory in grunt-ts with the fast option set to "watch" (default), it always runs against all the files saying: "Fast compile will not work when --out is specified. Ignoring fast compilation". 

If you do the same with the fast option set to "never" (default) and use newer, it will output this message:
"Warning: In task "build", either "files" or "out" should be used - not both."
I think that's why it wouldn't work for the issues #43 and #38

I've made a repository showing the problem with the out directory here: https://github.com/mvidailhet/grunt-ts-newer
 
But if you don't specify a "out" directory, "newer" or the fast compile from grunt-ts both only run against changed file as expected.

Hope that helped.

**Comment by mvidailhet** [comment]
For the jslint part, I found the problem. grunt-newer doesn't write cache files if there are errors (logic). 
My files had lint errors so that's why newer was always running against all the files.

**Comment by tschaub** [comment]
Thanks for the extra detail @mvidailhet.  So it sounds like we can close this as invalid regarding `grunt-tslint`.  Indeed the `newer` task uses the last **successful** run time when filtering source files.

If you could leave any comments for `grunt-ts` users on the other tickets, that would be great.  I'm not a `grunt-ts` user, so I'm not certain whether the issues are still valid (a change in `grunt-newer` would help) or not (`grunt-ts` config will help).
