### ISSUE TITLE
Save timestamps for individual files & re-run the task on change

### ISSUE THREAD

**Issue by mzgol** [tschaub/grunt-newer#78]
Sometimes when working with Git you need to checkout an earlier commit; running `newer:task:target` will then not regenerate the file since its timestamp is earlier than the one saved by `grunt-newer`.

It'd be useful if `grunt-newer` saved time stamps for every source file the task is run on and that it would re-run the task if the timestamp changed in any direction, not just if it got newer than the generated file.

**Comment by mzgol** [comment]
Hm, actually, it seems Git always updates timestamps so this shouldn't be an issue. Closing.

**Comment by tschaub** [comment]
Yeah, many things depend on [`git` always updating `mtime`](https://git.wiki.kernel.org/index.php/GitFaq#Why_isn.27t_Git_preserving_modification_time_on_files.3F) on changed files.
