### ISSUE TITLE
Has anyone developed a workflow using this with clean?

### ISSUE THREAD

**Issue by JeSuis** [tschaub/grunt-newer#82]
I want to use this with clean but only run clean if newer triggers the task to run like compass or requirejs

**Comment by tschaub** [comment]
I think "newer" is incompatible with "clean" since "newer" requires destination files (to compare mtime) and "clean" removes destination files.  But maybe I'm misunderstanding your issue.

**Comment by webdesignberlin** [comment]
Why the destination file is compared (mtime) and not the source file?

**Comment by andyexeter** [comment]
I'm trying to get something like this working myself. I'd like to run the `clean` task on my `build/img` directory but only on files older than in `src/img`, or if the file no longer exists in `src/img` - Is this possible with `newer`?
