### ISSUE TITLE
Assemble.io

### ISSUE THREAD

**Issue by kkashou** [tschaub/grunt-newer#92]
I have the newer tagged on for my assemble.io but I have to go to the page handlebars to actually have the newer task to work. I can't just modify my .json file or any other file except for page template. How can I get newer to work for assemble.io for every file and generate accordingly? 

Thanks

**Comment by kkashou** [comment]
Anyone?

**Comment by tschaub** [comment]
If your task is a 1:1 task (generating one destination file for every one source file), `grunt-newer` works by comparing modification times of the source file to modification times of the destination file.  If the source is newer, the task is run on that source file to generate the destination file.

I know of assemble.io, but I don't have time to put into debugging your particular issue.  So I can't say immediately if `grunt-newer` should be expected to work with assemble.  If someone else finds this and is interested in helping you debug, it would help them get started if you could provide an example project or config file.  It is especially time consuming to try to guess at how to reproduce an issue that someone reports.
